name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: self-hosted
    container:
      image: node:18
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust based on your project structure

      - name: Run tests
        run: |
          python -m unittest discover
